### ISSUE TITLE
Upstream bundle interface methods to protobuf-specs, and remove ProtobufBundle type

### ISSUE THREAD

**Issue by codysoyland** [sigstore/sigstore-go#243]
**Description**

The [`ProtobufBundle`](https://github.com/sigstore/sigstore-go/blob/main/pkg/bundle/bundle.go#L51-L55) type is largely a wrapper around the generated protobuf type [`Bundle`](https://github.com/sigstore/protobuf-specs/blob/main/gen/pb-go/bundle/v1/sigstore_bundle.pb.go#L259-L287):

```go
type ProtobufBundle struct {
	*protobundle.Bundle
	hasInclusionPromise bool
	hasInclusionProof   bool
}
```

The original purpose of this type was to add interface methods to `Bundle` to implement the [`SignedEntity`](https://github.com/sigstore/sigstore-go/blob/17ad99b4983b552fb861cdf28fea55fc1b707412/pkg/verify/interface.go#L55-L62) interface, before this repo was open-sourced, and while the `protobuf-specs` repo was unstable, or perhaps before the generated protobuf types were added there.

In order to use this library, a user who holds a `Bundle` type must first convert it to a `ProtobufBundle` type, using `NewProtobufBundle`. This conversion is simple, but adds boilerplate, and in many cases, it must also be first converted from JSON. We do have a helper func that facilitates this two-step conversion, [`LoadJSONFromPath`](https://github.com/sigstore/sigstore-go/blob/main/pkg/bundle/bundle.go#L161-L176), but users working with native protobuf types, such as using gRPC or Twirp, must always convert types, and the `ProtobufBundle` type doesn't have a clear meaning for users new to the library, and is hard to disambiguate from the actual "protobuf type".

The user experience of this library may be improved if we chose to upstream these interface methods into the `protobuf-specs` repo, in a file that resides next to the existing generated file. This would also make the upstream type easier to work with, allowing users to extract certificate chains and other types without requiring `sigstore-go`.

There are a few complications that might make this idea impractical. It would imply the upstreaming of some other interfaces and types to `protobuf-specs`, such as `verify.SignatureContent`, `verify.VerificationContent`, and `root.TrustedMaterial`, as these types are all bound to the `SignedEntity` interface.

In case this change would shift too much code up to `protobuf-specs` and complicate developement on `sigstore-go`, it could be argued that the generated `Bundle` type from `protobuf-specs` should be moved into `sigstore-go` and have the methods added here.

I would love to hear folk's thoughts on this prior to the 1.0 release, as I think it could make the public APIs cleaner.

**Comment by Hayden-IO** [comment]
I think the code in `protobuf-specs` should only be generated code, as it should reflect exactly what is defined in the protobufs. Upstreaming a number of interfaces and types will also negatively impact development velocity, and complicate handling code reviews and maintainership.

Have you explored if we could remove the `ProtobufBundle` type, and instead have helper methods that could transform JSON to the `Bundle` struct and vice-verse, validation helpers, etc, rather than extending the interface? This might be a far less clean API though, taking in generated code structs rather than `SignedEntity`.

As for moving the generated `Bundle` code out, I could see an argument for and against. We'd be able to implement the interface without wrapping the struct, but then we need to manage regenerating code every time the protobuf is updated (which occurs more frequently than expected due to the protobuf dependency updates).

Overall, I'm not against the `ProtobufBundle` type, I think it's a straightforward wrapper and easy to maintain.

**Comment by codysoyland** [comment]
> Upstreaming a number of interfaces and types will also negatively impact development velocity, and complicate handling code reviews and maintainership.

Yeah, that was kind of my concern toward the end of the description. 👍 

> Have you explored if we could remove the ProtobufBundle type, and instead have helper methods that could transform JSON to the Bundle struct and vice-verse, validation helpers, etc, rather than extending the interface?

I think I've thought about patterns that sound like this, but I agree it could be less clean, and I think `SignedEntity` is a good abstraction.

> but then we need to manage regenerating code every time the protobuf is updated

Agreed, it is nice having the stable types live in `protobuf-specs`.

I can close this out as `wontfix`, but while we are on this topic, is there any appetite for renaming `ProtobufBundle` to something like `SigstoreBundle` or just `Bundle`?

**Comment by Hayden-IO** [comment]
Yea, I would be supportive of renaming. I'd lean towards `Bundle` - while it's overloaded, we want the only usage of "bundle" within Sigstore to refer to this new bundle format.
