### ISSUE TITLE
Error initializing `SignedEntityVerifier` using `WithSignedCertificateTimestamps` option

### ISSUE THREAD

**Issue by malancas** [sigstore/sigstore-go#83]
**Description**

I received the following error message while initializing a SignedEntityVerifier to use with the Public Good instance: "when initializing a new SignedEntityVerifier, you must specify at least one of WithObserverTimestamps(), WithSignedTimestamps(), WithIntegratedTimestamps(), or WithoutAnyObserverTimestampsInsecure()".

The [example in the verify doc](https://github.com/sigstore/sigstore-go/blob/main/docs/verification.md) uses the `verify.WithSignedCertificateTimestamps` option  when initializing a new `SignedEntityVerifier` for use with Public Good. I tried using this option with  `verify.NewSignedEntityVerifier`  but I get the same error. Reading through the [verifier code](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/signed_entity.go#L205), it looks like the code does not check for this option when validating options used with `NewSignedEntityVerifier`. Should I be using a different option?

**Version**

v0.1.0

**Comment by Hayden-IO** [comment]
Ah, the example doc needs to be updated. `WithTransparencyLog` is no longer sufficient to fetch a timestamp, because we split out log verification from timestamp verification. You can add `WithObserverTimestamp` to verify a timestamp from either the log or TSA, `WithSignedTimestamps` for just the TSA, `WithIntegratedTimestamps` for just the log, or `WithoutAnyObserverTimestampsInsecure` if you don't need a timestamp.

**Comment by malancas** [comment]
Great, I'll update my code accordingly, thanks for the information.
